name: sonarcloud

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - main

jobs:

  sonarcloud:
    name: SonarCloud
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.12'
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - name: Install the project dependencies
        run: uv sync --all-groups
      - name: Run the automated tests
        run: uv run pytest --cov --cov-report term --cov-report xml --junitxml=xunit-result.xml tests/
      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.DRIPPY_GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
